"""create sectors and burial spaces

Revision ID: a8b363f3c8e9
Revises: cf8b65f65896
Create Date: 2026-08-07 18:26:07.714456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b363f3c8e9'
down_revision = 'cf8b65f65896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sectors_code'), ['code'], unique=True)

    op.create_table('burial_spaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('block_letter', sa.String(length=1), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('location_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'OCCUPIED', 'BLOCKED', 'MAINTENANCE', name='burial_space_status'), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('location_number BETWEEN 1 AND 20', name='ck_burial_space_location_number'),
    sa.CheckConstraint('row_number BETWEEN 1 AND 20', name='ck_burial_space_row_number'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector_id', 'block_letter', 'row_number', 'location_number', name='uq_burial_space_location')
    )
    with op.batch_alter_table('burial_spaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_burial_spaces_sector_id'), ['sector_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('burial_spaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_burial_spaces_sector_id'))

    op.drop_table('burial_spaces')
    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sectors_code'))

    op.drop_table('sectors')
    # ### end Alembic commands ###
